name: nookknack
description: A new Flutter application.


version: 1.0.2+4

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_statusbarcolor: ^0.2.3
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.4+2
  google_fonts: ^0.3.10
  shared_preferences: ^0.5.6+3
  flutter_screenutil: ^1.1.0
  fluttertoast: ^4.0.1
  firebase_auth: ^0.16.0
  font_awesome_flutter: ^8.8.1
  google_sign_in: ^4.4.4
  sliding_up_panel: ^1.0.2
  flutter_masked_text: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/